title: Pengzhi Sun' Blog
owner: Pengzhi Sun
email: pengzhisun@live.com
description: >- # this means to ignore newlines
  I'm Pengzhi Sun, Senior Software Engineer from Microsoft Azure China Engineer
  Team, this is my personal technical blog for Azure related topics.

github_username: pengzhisun

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
